version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: bash -c "poetry run python app/main.py"
    restart: always
    links:
      - postgres
      - redis
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - app_network


  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=2453
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fickel
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    command: "poetry run celery -A app.celery_worker worker -l info"
    restart: always
    depends_on:
      - redis
      - api

volumes:
  postgres_data:


networks:
  app_network: